name: test

on: push

jobs:
  test:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: Set up MySQL
        run: docker-compose up -d

      - name: Build app image
        run: docker-compose exec -T app go test ./...
