name: test

on: push

jobs:
  test:
    runs-on: ubuntu-20.04

    services:
      db:
        image: mysql:5.7
        ports:
          - 3306:3306
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: 1

    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Install tools
        run: sudo apt-get update -qq && sudo apt-get install --no-install-recommends -y default-mysql-client

      - name: Set up MySQL
        run: mysql -h 127.0.0.1 -u root < ./db/init.sql

      - name: Build app image
        run: docker image build --tag app app

      - name: Run app container
        run: docker container run -d -p 0.0.0.0:8888:8888 app

      - name: Test
        run: go test ./...
